# Generated by Django 2.2 on 2020-06-30 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_allocation',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_inspector', to=settings.AUTH_USER_MODEL)),
                ('salesmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_salesmen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('allocations', models.ManyToManyField(through='portal.Allocation', to='portal.Order')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Product'),
        ),
    ]
