# Generated by Django 2.2 on 2020-07-04 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path_image', models.TextField(blank=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_allocation',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tbl_environment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Environment')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_inspector', to=settings.AUTH_USER_MODEL)),
                ('salesmen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_salesmen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
            ],
            options={
                'db_table': 'tbl_room',
            },
        ),
        migrations.CreateModel(
            name='ProductBelongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Product')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Room')),
            ],
            options={
                'db_table': 'tbl_product_belongs',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allocations',
            field=models.ManyToManyField(through='portal.Allocation', to='portal.Room'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Product'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='product_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ProductBelongs'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Room'),
        ),
    ]
