# Generated by Django 2.2 on 2020-06-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='path_image',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
