# Generated by Django 2.2 on 2020-07-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='order',
        ),
        migrations.CreateModel(
            name='AllocationRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Room')),
            ],
            options={
                'db_table': 'tbl_allocation_room',
            },
        ),
        migrations.AddField(
            model_name='allocationlabel',
            name='allocation_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.AllocationRoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocationproduct',
            name='allocation_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.AllocationRoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rooms',
            field=models.ManyToManyField(through='portal.AllocationRoom', to='portal.Room'),
        ),
    ]
