# Generated by Django 2.2 on 2020-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200711_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='florense/order_files/'),
        ),
    ]
