# Generated by Django 2.2 on 2020-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_allocation_path_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='path_image',
            field=models.TextField(blank=True),
        ),
    ]
