# Generated by Django 2.2 on 2020-07-14 02:19

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_allocationproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationproduct',
            name='path_image',
        ),

    ]
