# Generated by Django 2.2 on 2020-07-15 00:41

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200713_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocationproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to=portal.models.get_product_images_path),
        ),
    ]
